### ISSUE TITLE
Question: how to see the diagram of a .klaviz file

### ISSUE THREAD

**Issue by hrj** [OpenKieler/klassviz#2]
First off, I am thrilled to discover this project! I had spent a lot of time last week in trying to find something similar but had finally given up. And then I discovered this today, just by chance!

I am able to generate class diagrams from selection very easily. Some questions:

1. How do I save the auto-generated class diagram from my selection into a `.klaviz` file?

2. When I create a `.klaviz` file manually, I am able to see only the text version of edit. How do I see the corresponding diagram for it?

**Comment by hrj** [comment]
Oh, I found the answer to the second question just after posting it :sweat_smile: 

From the `View Management` Dialog I had to tick the `Create graphical views of textual specifications` option.

**Comment by spoenemann** [comment]
I think it's not possible to create a .klaviz from a package explorer selection, but yes, it would be nice.

**Comment by le-cds** [comment]
I'm closing this issue since it's mainly questions. The generate-from-selection feature is now tracked in #4.
